### ISSUE TITLE
binding.pry doesn't work

### ISSUE THREAD

**Issue by jmuheim** [ranmocy/guard-rails#24]
When starting rails server on the console, I can add a `binding.pry` wherever I want it, hit reload, and then execution is halted at this line and I can interact with pry in the given context.

With Guard-Rails, this doesn't seem to work. The `binding.pry` is recognised, but simply omitted, which means that execution is continued without giving me the chance to interact with pry.

The output (which proves that `binding.pry` is recognised, see `=> 5: - binding.pry`):

```

Frame number: 0/106

From: /Users/josh/Documents/Work/MuheimWebdesign/base/app/views/dashboards/show.html.slim @ line 5 ActionView::CompiledTemplates#_app_views_dashboards_show_html_slim__130432664906313828_70093845884840:

    1: h1
    2:   i.glyphicon.glyphicon-home
    3:   |Dashboards#show
    4: 
 => 5: - binding.pry

[1] base(#<#<Class:0x007f7ffd913c80>>) »  
  Rendered dashboards/show.html.slim within layouts/application (116.0ms)
  Rendered app/cells/mini_hub/show.html.slim (3.7ms)
Completed 200 OK in 255ms (Views: 230.1ms | ActiveRecord: 0.0ms)
  Rendered /Users/josh/.rvm/gems/ruby-2.0.0-p353@base/gems/xray-rails-0.1.12/app/views/_xray_bar.html.erb (8.8ms)
12:21:29 - INFO - Browser disconnected.
12:21:30 - INFO - Browser connected.
12:21:45 - INFO - Browser connected.
```

This question on stackoverflow asks the same, and is over a year old already:
http://stackoverflow.com/questions/14153585/guard-rails-not-providing-repl-for-binding-pry

It would be really useful to have the rails output and guard input in the same window, but without pry, I'm not able to do my work.

Thanks a lot for help.

**Comment by westonganger** [comment]
try using gem pry-remote

**Comment by atd** [comment]
For those who might be interested, I implemented a solution using `pry-remote`

https://github.com/atd/guard-rails

I don't care about blocking the whole `guard` process because I want to focus on debugging the code and I can live with handling file modifications after I exit `pry-remote`

**Comment by suranyami** [comment]
This issue doesn't seem to be a problem any more.

`binding.pry` works as expected using rails 5.x, ruby 2.4.

Should the documentation in the `README.md`?

**Comment by timolehto** [comment]
I'm having this same issue as I'm upgrading from Rails 5 -> 6 🤔
