### ISSUE TITLE
Can't connect to master. Run zeus start first.

### ISSUE THREAD

**Issue by westonganger** [ranmocy/guard-rails#40]
I am trying to use the zeus: true option

I am getting the error: Can't connect to master. Run zeus start first.

Zeus is installed globally, in the meantime I am using guard-zeus but i think using guard-rails with that doesnt have the server restart speed advantages.

**Comment by ranmocy** [comment]
Sorry for late reply.
I think the problem does happen between `guard-zeus` and `guard-rails`. Seems that when `guard-rails` starts, `guard-zeus` usually won't be ready since it's slower.

Do you think it's a good idea to have a loop to keep trying connect it?

**Comment by westonganger** [comment]
Should I even need Guard-Zeus of this is working correctly? I think a delay and/or a loop would work great.

**Comment by ranmocy** [comment]
The new 0.7.2 version waits for zeus to start. Check it out!
