### ISSUE TITLE
Rails 5.1 rake dev:cache interfering with restarting the puma server

### ISSUE THREAD

**Issue by skunkworker** [ranmocy/guard-rails#47]
With Rails 5.1 adding the `rake dev:cache` command. [Code here](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/railties/lib/rails/dev_caching.rb)
the default strategy of `watch('tmp/caching-dev.txt')` would fail when running `rake dev:cache` in another terminal window. As it would complain that the pid already exists. I looked into the implementation in the rails master branch and it turns out that by default it is removing the pid file on `tmp/pids/server.pid`. Adding this config to the guardfile fixed the issue. Is this a rails issue not respecting other pid files?

**Comment by skunkworker** [comment]
Current config

```guard 'rails', port: 3000, host: '0.0.0.0', force_run: true, pid_file: 'tmp/pids/server.pid' do
  watch('Gemfile.lock')
  watch(%r{^(config|lib)/.*})

  watch('tmp/caching-dev.txt') # for Rails 5.1 testing of caching.
end
```

**Comment by ranmocy** [comment]
After some tests, I believe this is a Rails bug. Created the Rails issue [here](https://github.com/rails/rails/issues/29306).
The issue exists regardless guard-rails. Even simple `rails s -P tmp/pids/dev.pid` would reproduce the issue.

BTW, `watch('tmp/caching-dev.txt')` is not necessary. Rails would trigger the restarting by itself. My config:
```
guard 'rails', pid_file: 'tmp/pids/server.pid' do
  watch('Gemfile.lock')
  watch(%r{^(config|lib)/.*})
end
```

**Comment by skunkworker** [comment]
@ranmocy that's one of the conclusions I came to as well, it seems as though they hardcode the PID file in multiple places and don't respect other locations.

**Comment by skunkworker** [comment]
And thanks for the input about not having to watch the `caching-dev.txt` file, just the pid going is enough it seems to trigger the restarting. 👍
